/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.eam.ingesoft.pa.standalone.gui;

import java.util.Date;
import java.util.List;

import javax.naming.NamingException;
import javax.swing.JOptionPane;

import co.edu.eam.ingesoft.avanzada.persistencia.edentidades.CreditCard;
import co.edu.eam.ingesoft.avanzada.persistencia.edentidades.Customer;
import co.edu.eam.ingesoft.avanzada.persistencia.edentidades.Franchise;
import co.edu.eam.ingesoft.avanzada.persistencia.edentidades.Product;
import co.edu.eam.ingesoft.avanzada.persistencia.edentidades.SavingAccount;
import co.edu.eam.ingesoft.avanzada.persistencia.edentidades.Usuario;
import co.edu.eam.ingesoft.pa.negocio.exception.ExcepcionNegocio;
import co.edu.eam.ingesoft.pa.standalone.controlador.ControladorCustomer;
import co.edu.eam.ingesoft.pa.standalone.controlador.ControladorVentanaGestionProducto;

/**
 *
 * @author LuchoBolivar
 */
public class GestionCustomer extends javax.swing.JFrame {

	private ControladorCustomer controladorCliente;
	private ControladorVentanaGestionProducto controladorProduc;

	/**
	 * Creates new form RegistroCustomer
	 */
	public GestionCustomer() {
		initComponents();
		try {
			controladorCliente = new ControladorCustomer();
			controladorProduc = new ControladorVentanaGestionProducto();
		} catch (NamingException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		llenarCombofranchise();
		jTCantidadT.setEnabled(false);
		jTNombreB.setEditable(false);
		jTApellidosB.setEditable(false);
		jTNomUsuario.setEditable(false);
		jTUsuPassword.setEditable(false);
		jTInfoCuenta.setEditable(false);
		jTInfoTarjeta.setEditable(false);
				
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTGestion = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jBRegistrar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jTNumeroIdentificacion = new javax.swing.JTextField();
        jCTipoDeDocumento = new javax.swing.JComboBox<>();
        jTApellidos = new javax.swing.JTextField();
        jTNombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLNombreB = new javax.swing.JLabel();
        jLApellidoB = new javax.swing.JLabel();
        jTApellidosB = new javax.swing.JTextField();
        jTNombreB = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTNomUsuario = new javax.swing.JTextField();
        jTUsuPassword = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTNumIdB = new javax.swing.JTextField();
        jBBus = new javax.swing.JButton();
        jLTipoDocumentoB = new javax.swing.JLabel();
        jCIdTypeB = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jPRequisitos = new javax.swing.JPanel();
        jLNumIdP = new javax.swing.JLabel();
        jLTipoIdP = new javax.swing.JLabel();
        jTNumIdP = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBBuscarP = new javax.swing.JButton();
        jPProductos = new javax.swing.JPanel();
        jPTarjetasCredit = new javax.swing.JPanel();
        jBCrearTP = new javax.swing.JButton();
        jCFranchise = new javax.swing.JComboBox<>();
        jLCantidadTarjeta = new javax.swing.JLabel();
        jTCantidadT = new javax.swing.JTextField();
        jPanelInfoTarjeta = new javax.swing.JPanel();
        jTInfoTarjeta = new javax.swing.JTextField();
        jPCuentasAhorro = new javax.swing.JPanel();
        jBCrearP = new javax.swing.JButton();
        jPanelInfoCuenta = new javax.swing.JPanel();
        jTInfoCuenta = new javax.swing.JTextField();
        jPNuevoP = new javax.swing.JPanel();
        jBNuevoP = new javax.swing.JButton();
        jPGesionPro = new javax.swing.JPanel();
        jBConsulPro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));

        jTGestion.setBackground(new java.awt.Color(0, 102, 102));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jBRegistrar.setForeground(new java.awt.Color(0, 102, 102));
        jBRegistrar.setText("Registrar");
        jBRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jBRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Requisitos del Registro"));

        jLabel1.setText("Nombres :");

        jLabel2.setText("Apellidos :");

        jLabel3.setText("Tipo de Documento :");

        jLabel4.setText("Numero de documento :");

        jLabel7.setText("Nombre de Usuario :");

        jLabel8.setText("Contraseña :");

        jCTipoDeDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo Identificacion", "Pasaporte", "Cedula", "Tarjeta de Identidad" }));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(83, 83, 83)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTNombre)
                    .addComponent(jTApellidos)
                    .addComponent(jTNumeroIdentificacion)
                    .addComponent(jCTipoDeDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCTipoDeDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTNumeroIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jTGestion.addTab("Registrar Cliente", jPanel1);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultado Busqueda"));

        jLNombreB.setText("Nombres :");

        jLApellidoB.setText("Apellidos :");

        jLabel9.setText("Usuario :");

        jLabel10.setText("Contraseña :");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNombreB)
                    .addComponent(jLApellidoB)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(148, 148, 148)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTNombreB, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jTApellidosB)
                    .addComponent(jTNomUsuario)
                    .addComponent(jTUsuPassword))
                .addGap(61, 61, 61))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombreB)
                    .addComponent(jTNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTApellidosB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLApellidoB))
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTUsuPassword, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Requisitos Busqueda"));

        jLabel5.setText("Nuemero De Documento :");

        jBBus.setForeground(new java.awt.Color(0, 102, 102));
        jBBus.setText("Buscar");
        jBBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBusActionPerformed(evt);
            }
        });

        jLTipoDocumentoB.setText("Tipo de Documento :");

        jCIdTypeB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo Identificacion", "Pasaporte", "Cedula", "Tarjeta de Identidad" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLTipoDocumentoB))
                .addGap(64, 64, 64)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTNumIdB)
                    .addComponent(jCIdTypeB, 0, 265, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBBus, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTNumIdB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTipoDocumentoB)
                    .addComponent(jCIdTypeB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jBBus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTGestion.addTab("Buscar Cliente", jPanel3);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));

        jPRequisitos.setBackground(new java.awt.Color(255, 255, 255));
        jPRequisitos.setBorder(javax.swing.BorderFactory.createTitledBorder("Requisitos Para Operacion"));

        jLNumIdP.setText("Numero de identificacion :");

        jLTipoIdP.setText("Tipo de Identificacion :");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo Identificacion", "Pasaporte", "Cedula", "Tarjeta de Identidad" }));

        jBBuscarP.setBackground(new java.awt.Color(0, 102, 102));
        jBBuscarP.setForeground(new java.awt.Color(0, 102, 102));
        jBBuscarP.setText("Buscar");
        jBBuscarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPRequisitosLayout = new javax.swing.GroupLayout(jPRequisitos);
        jPRequisitos.setLayout(jPRequisitosLayout);
        jPRequisitosLayout.setHorizontalGroup(
            jPRequisitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRequisitosLayout.createSequentialGroup()
                .addGroup(jPRequisitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPRequisitosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPRequisitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLNumIdP, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLTipoIdP))
                        .addGap(18, 18, 18)
                        .addGroup(jPRequisitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTNumIdP, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPRequisitosLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jBBuscarP)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPRequisitosLayout.setVerticalGroup(
            jPRequisitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPRequisitosLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPRequisitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNumIdP)
                    .addComponent(jTNumIdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPRequisitosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLTipoIdP)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPProductos.setBackground(new java.awt.Color(255, 255, 255));
        jPProductos.setBorder(javax.swing.BorderFactory.createTitledBorder("Productos"));
        jPProductos.setEnabled(false);

        jPTarjetasCredit.setBackground(new java.awt.Color(255, 255, 255));
        jPTarjetasCredit.setBorder(javax.swing.BorderFactory.createTitledBorder("Tarjetas de Credito"));
        jPTarjetasCredit.setEnabled(false);

        jBCrearTP.setForeground(new java.awt.Color(0, 102, 102));
        jBCrearTP.setText("Crear");
        jBCrearTP.setEnabled(false);
        jBCrearTP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearTPActionPerformed(evt);
            }
        });

        jCFranchise.setEnabled(false);

        jLCantidadTarjeta.setText("Cantidad :");
        jLCantidadTarjeta.setEnabled(false);

        jTCantidadT.setEnabled(false);

        jPanelInfoTarjeta.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero Tarjeta"));
        jPanelInfoTarjeta.setEnabled(false);

        jTInfoTarjeta.setEnabled(false);

        javax.swing.GroupLayout jPanelInfoTarjetaLayout = new javax.swing.GroupLayout(jPanelInfoTarjeta);
        jPanelInfoTarjeta.setLayout(jPanelInfoTarjetaLayout);
        jPanelInfoTarjetaLayout.setHorizontalGroup(
            jPanelInfoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoTarjetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTInfoTarjeta)
                .addContainerGap())
        );
        jPanelInfoTarjetaLayout.setVerticalGroup(
            jPanelInfoTarjetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoTarjetaLayout.createSequentialGroup()
                .addComponent(jTInfoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPTarjetasCreditLayout = new javax.swing.GroupLayout(jPTarjetasCredit);
        jPTarjetasCredit.setLayout(jPTarjetasCreditLayout);
        jPTarjetasCreditLayout.setHorizontalGroup(
            jPTarjetasCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTarjetasCreditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCFranchise, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPTarjetasCreditLayout.createSequentialGroup()
                .addGroup(jPTarjetasCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPTarjetasCreditLayout.createSequentialGroup()
                        .addGroup(jPTarjetasCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPTarjetasCreditLayout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLCantidadTarjeta))
                            .addGroup(jPTarjetasCreditLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPTarjetasCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jBCrearTP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(jTCantidadT, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addGap(0, 35, Short.MAX_VALUE))
                    .addComponent(jPanelInfoTarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPTarjetasCreditLayout.setVerticalGroup(
            jPTarjetasCreditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTarjetasCreditLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCFranchise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jLCantidadTarjeta)
                .addGap(18, 18, 18)
                .addComponent(jTCantidadT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jBCrearTP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelInfoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPCuentasAhorro.setBackground(new java.awt.Color(255, 255, 255));
        jPCuentasAhorro.setBorder(javax.swing.BorderFactory.createTitledBorder("Cuentas de Ahorro"));
        jPCuentasAhorro.setEnabled(false);

        jBCrearP.setForeground(new java.awt.Color(0, 102, 102));
        jBCrearP.setText("Crear");
        jBCrearP.setEnabled(false);
        jBCrearP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearPActionPerformed(evt);
            }
        });

        jPanelInfoCuenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Numero De Cuenta"));
        jPanelInfoCuenta.setEnabled(false);

        jTInfoCuenta.setEnabled(false);

        javax.swing.GroupLayout jPanelInfoCuentaLayout = new javax.swing.GroupLayout(jPanelInfoCuenta);
        jPanelInfoCuenta.setLayout(jPanelInfoCuentaLayout);
        jPanelInfoCuentaLayout.setHorizontalGroup(
            jPanelInfoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTInfoCuenta, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanelInfoCuentaLayout.setVerticalGroup(
            jPanelInfoCuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInfoCuentaLayout.createSequentialGroup()
                .addComponent(jTInfoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPCuentasAhorroLayout = new javax.swing.GroupLayout(jPCuentasAhorro);
        jPCuentasAhorro.setLayout(jPCuentasAhorroLayout);
        jPCuentasAhorroLayout.setHorizontalGroup(
            jPCuentasAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCuentasAhorroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInfoCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPCuentasAhorroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jBCrearP, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPCuentasAhorroLayout.setVerticalGroup(
            jPCuentasAhorroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCuentasAhorroLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jBCrearP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jPanelInfoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout jPProductosLayout = new javax.swing.GroupLayout(jPProductos);
        jPProductos.setLayout(jPProductosLayout);
        jPProductosLayout.setHorizontalGroup(
            jPProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProductosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPTarjetasCredit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jPCuentasAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPProductosLayout.setVerticalGroup(
            jPProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProductosLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPCuentasAhorro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPTarjetasCredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPNuevoP.setBackground(new java.awt.Color(255, 255, 255));
        jPNuevoP.setBorder(javax.swing.BorderFactory.createTitledBorder("Mas Opciones"));
        jPNuevoP.setEnabled(false);

        jBNuevoP.setForeground(new java.awt.Color(0, 102, 102));
        jBNuevoP.setText("Escoger Nuevo Cliente");
        jBNuevoP.setEnabled(false);
        jBNuevoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNuevoPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPNuevoPLayout = new javax.swing.GroupLayout(jPNuevoP);
        jPNuevoP.setLayout(jPNuevoPLayout);
        jPNuevoPLayout.setHorizontalGroup(
            jPNuevoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNuevoPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBNuevoP)
                .addGap(23, 23, 23))
        );
        jPNuevoPLayout.setVerticalGroup(
            jPNuevoPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNuevoPLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jBNuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPGesionPro.setBackground(new java.awt.Color(255, 255, 255));
        jPGesionPro.setBorder(javax.swing.BorderFactory.createTitledBorder("Opcines Producto"));
        jPGesionPro.setEnabled(false);

        jBConsulPro.setForeground(new java.awt.Color(0, 102, 102));
        jBConsulPro.setText("Gestionar Productos Obtenidos");
        jBConsulPro.setEnabled(false);
        jBConsulPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsulProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPGesionProLayout = new javax.swing.GroupLayout(jPGesionPro);
        jPGesionPro.setLayout(jPGesionProLayout);
        jPGesionProLayout.setHorizontalGroup(
            jPGesionProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGesionProLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBConsulPro, javax.swing.GroupLayout.PREFERRED_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPGesionProLayout.setVerticalGroup(
            jPGesionProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPGesionProLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jBConsulPro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPGesionPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jPNuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jPRequisitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPRequisitos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPGesionPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPNuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTGestion.addTab("Contratar producto para cliente", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 616, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void jBConsulProActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBConsulProActionPerformed
		String tipoId = (String) jComboBox1.getSelectedItem();
		String ced = jTNumIdP.getText();
		Customer cliente = controladorCliente.buscarCustomer(ced, tipoId);

		ConsultaProductos consul = new ConsultaProductos(cliente);
		consul.setVisible(true);
	}// GEN-LAST:event_jBConsulProActionPerformed

	private void jBCrearTPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBCrearTPActionPerformed

		if (jTCantidadT.getText().isEmpty()) {
			JOptionPane.showMessageDialog(null, "Por favor indique la cantidad de la tarjeta de credito que requiere");
		} else {
			double cantidad = Double.parseDouble(jTCantidadT.getText());
			String ced = jTNumIdP.getText();
			String tipoId = (String) jComboBox1.getSelectedItem();
			Customer cliente = controladorCliente.buscarCustomer(ced, tipoId);
			int numTarjetas = controladorProduc.validarProductosTarjetaCredit(cliente);
			Franchise franquisi = (Franchise) jCFranchise.getSelectedItem();

			Date fecha = new Date();

			Date fechaVenci = new Date();
			fechaVenci.setYear(fecha.getYear() + 4);

			CreditCard tCredito = new CreditCard();
			tCredito.setCustomer(cliente);
			tCredito.setExpeditionDate(fecha);
			tCredito.setExpirationDate(fechaVenci);
			tCredito.setCvc(controladorProduc.cvcNumAle());
			tCredito.setFranchise(franquisi);
			tCredito.setNumber(controladorProduc.numeroTarjeta());
			tCredito.setAmmount(cantidad);
			tCredito.setCantidadRestante(cantidad);

			if (numTarjetas < 2) {

				controladorProduc.registrarTarjeta(tCredito);
				jTInfoTarjeta.setText(tCredito.getNumber());
				JOptionPane.showMessageDialog(null, " FELICITACIONES, has adquirido una trajeta de credito ");
			} else {
				JOptionPane.showMessageDialog(null, "el cliente ya tiene el limete de cuentas de tarjetas creadas");

			}
		}

	}// GEN-LAST:event_jBCrearTPActionPerformed

	private void jBCrearPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBCrearPActionPerformed

		String ced = jTNumIdP.getText();
		String tipoId = (String) jComboBox1.getSelectedItem();
		Customer cliente = controladorCliente.buscarCustomer(ced, tipoId);
		int numCuentas = controladorProduc.validarCuentaAhorro(cliente);
		Date fecha = new Date();

		SavingAccount cuenta = new SavingAccount();
		cuenta.setAmmount(0);
		cuenta.setCustomer(cliente);
		cuenta.setExpeditionDate(fecha);
		cuenta.setNumber(controladorProduc.numeroCuentaAhorro());
		cuenta.setSavingInterest(200);

		if (numCuentas < 3) {

			controladorProduc.registrarCuenta(cuenta);
			jTInfoCuenta.setText(cuenta.getNumber());
			jTCantidadT.setText(null);
			JOptionPane.showMessageDialog(null, "FELICITACIONES, has adquirido una cuenta de ahorro");
		
		} else {
			JOptionPane.showMessageDialog(null, "el Cliente ya tiene el limete de cuenta de ahorro creadas");
		}
	}// GEN-LAST:event_jBCrearPActionPerformed

	private void jBBuscarPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBBuscarPActionPerformed
		try {
			String ced = jTNumIdP.getText();
			String idType = (String) jComboBox1.getSelectedItem();
			Customer cliente = controladorCliente.buscarCustomer(ced, idType);
			if (cliente != null) {

				jPTarjetasCredit.setEnabled(true);
				jPNuevoP.setEnabled(true);
				jBNuevoP.setEnabled(true);
				jBCrearP.setEnabled(true);
				jBCrearTP.setEnabled(true);
				jPCuentasAhorro.setEnabled(true);
				jPProductos.setEnabled(true);
				jCFranchise.setEnabled(true);
				jPGesionPro.setEnabled(true);
				jBConsulPro.setEnabled(true);
				jPRequisitos.setEnabled(false);
				jLNumIdP.setEnabled(false);
				jLTipoIdP.setEnabled(false);
				jTNumIdP.setEnabled(false);
				jComboBox1.setEnabled(false);
				jBBuscarP.setEnabled(false);
				jTGestion.setEnabled(false);
				jTCantidadT.setEnabled(true);
				jTCantidadT.setEnabled(true);
				jTInfoCuenta.setEnabled(true);
				jTInfoTarjeta.setEnabled(true);
				jPanelInfoCuenta.setEnabled(true);
				jPanelInfoTarjeta.setEnabled(true);
				jLCantidadTarjeta.setEnabled(true);
				

			} else {
				JOptionPane.showMessageDialog(null, "El cliente no se encuentra en la base de datos");
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
	}// GEN-LAST:event_jBBuscarPActionPerformed

	private void jBNuevoPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBNuevoPActionPerformed

		jPTarjetasCredit.setEnabled(false);
		jPNuevoP.setEnabled(false);
		jBNuevoP.setEnabled(false);
		jBCrearP.setEnabled(false);
		jBCrearTP.setEnabled(false);
		jPCuentasAhorro.setEnabled(false);
		jPProductos.setEnabled(false);
		jPRequisitos.setEnabled(true);
		jLNumIdP.setEnabled(true);
		jLTipoIdP.setEnabled(true);
		jTNumIdP.setEnabled(true);
		jComboBox1.setEnabled(true);
		jBBuscarP.setEnabled(true);
		jComboBox1.setSelectedIndex(0);
		jTNumIdP.setText(null);
		jCFranchise.setEnabled(false);
		jPGesionPro.setEnabled(false);
		jBConsulPro.setEnabled(false);
		jTGestion.setEnabled(true);
		jTCantidadT.setEnabled(false);
		jTCantidadT.setEnabled(false);
		jTInfoCuenta.setEnabled(false);
		jTInfoTarjeta.setEnabled(false);
		jPanelInfoCuenta.setEnabled(false);
		jPanelInfoTarjeta.setEnabled(false);
		jLCantidadTarjeta.setEnabled(false);
		jTInfoCuenta.setText(null);
		jTInfoTarjeta.setText(null);

	}// GEN-LAST:event_jBNuevoPActionPerformed

	private void jBRegistrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBRegistrarActionPerformed
		try {
			if (jCTipoDeDocumento.getSelectedIndex() == 0 || jTApellidos.getText().isEmpty()
					|| jTNumeroIdentificacion.getText().isEmpty() || jTNombre.getText().isEmpty()) {
				JOptionPane.showMessageDialog(null, "Debe llenar todos los requisitos de registro");
			} else {
				Customer cliente = new Customer();
				cliente.setIdNum(jTNumeroIdentificacion.getText());
				cliente.setIdType((String) jCTipoDeDocumento.getSelectedItem());
				cliente.setName(jTNombre.getText());
				cliente.setLastName(jTApellidos.getText());
				
				Usuario usu = new Usuario();
				usu.setCustomer(cliente);
				usu.setPassword(jPasswordField1.getText());
				usu.setUserName(jTextField1.getText());

				controladorCliente.crearCustomer(cliente);
				controladorCliente.crearUsuario(usu);
				JOptionPane.showMessageDialog(null, " El Cliente a sido Creado");

				jTApellidos.setText(null);
				jCTipoDeDocumento.setSelectedIndex(0);
				jTNombre.setText(null);
				jTNumeroIdentificacion.setText(null);
				jTextField1.setText(null);
				jPasswordField1.setText(null);
			}

		} catch (Exception e) {
			e.printStackTrace();
		}

	}// GEN-LAST:event_jBRegistrarActionPerformed

	private void jBBusActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jBBusActionPerformed
		try {
			String ced = jTNumIdB.getText();
			String idType = (String) jCIdTypeB.getSelectedItem();
			Customer cliente = controladorCliente.buscarCustomer(ced, idType);
			if (cliente != null) {

				jTNombreB.setText(cliente.getName());
				jTApellidosB.setText(cliente.getLastName());

			} else {
				JOptionPane.showMessageDialog(null, "el cliente que busca no se encuentra registrado ");
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
		}
	}// GEN-LAST:event_jBBusActionPerformed

	private void llenarCombofranchise() {

		List<Franchise> list = controladorCliente.listaFranchise1();
		for (Franchise franqui : list) {
			jCFranchise.addItem(franqui);
			// if (!list.isEmpty()) {
			// jCFranchise.getSelectionModel().selectFirst();
			// }
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBus;
    private javax.swing.JButton jBBuscarP;
    private javax.swing.JButton jBConsulPro;
    private javax.swing.JButton jBCrearP;
    private javax.swing.JButton jBCrearTP;
    private javax.swing.JButton jBNuevoP;
    private javax.swing.JButton jBRegistrar;
    private javax.swing.JComboBox jCFranchise;
    private javax.swing.JComboBox jCIdTypeB;
    private javax.swing.JComboBox jCTipoDeDocumento;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLApellidoB;
    private javax.swing.JLabel jLCantidadTarjeta;
    private javax.swing.JLabel jLNombreB;
    private javax.swing.JLabel jLNumIdP;
    private javax.swing.JLabel jLTipoDocumentoB;
    private javax.swing.JLabel jLTipoIdP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPCuentasAhorro;
    private javax.swing.JPanel jPGesionPro;
    private javax.swing.JPanel jPNuevoP;
    private javax.swing.JPanel jPProductos;
    private javax.swing.JPanel jPRequisitos;
    private javax.swing.JPanel jPTarjetasCredit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelInfoCuenta;
    private javax.swing.JPanel jPanelInfoTarjeta;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTApellidos;
    private javax.swing.JTextField jTApellidosB;
    private javax.swing.JTextField jTCantidadT;
    private javax.swing.JTabbedPane jTGestion;
    private javax.swing.JTextField jTInfoCuenta;
    private javax.swing.JTextField jTInfoTarjeta;
    private javax.swing.JTextField jTNomUsuario;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTNombreB;
    private javax.swing.JTextField jTNumIdB;
    private javax.swing.JTextField jTNumIdP;
    private javax.swing.JTextField jTNumeroIdentificacion;
    private javax.swing.JTextField jTUsuPassword;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
